"""empty message

Revision ID: cfb146de80f0
Revises: 
Create Date: 2026-01-14 18:17:27.619134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb146de80f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('di_avaliacoes',
    sa.Column('di_avaliacao_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('data_avaliacao', sa.DateTime(), nullable=True),
    sa.Column('nota', sa.String(), nullable=True),
    sa.Column('recurso', sa.String(), nullable=True),
    sa.Column('data_recurso', sa.DateTime(), nullable=True),
    sa.Column('avaliador_nome', sa.String(), nullable=True),
    sa.Column('tipo_avaliacao_nome', sa.String(), nullable=True),
    sa.Column('tipo_avaliacao_tipo', sa.String(), nullable=True),
    sa.Column('tipo_avaliacao_nota_descricao', sa.String(), nullable=True),
    sa.Column('plano_entrega_id', sa.String(), nullable=True),
    sa.Column('plano_trabalho_consolidacao_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('di_avaliacao_id')
    )
    op.create_table('di_entregas',
    sa.Column('di_entregas_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('homologado', sa.Integer(), nullable=True),
    sa.Column('progresso_esperado', sa.Float(), nullable=True),
    sa.Column('progresso_realizado', sa.Float(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('destinatario', sa.String(), nullable=True),
    sa.Column('meta_tipo', sa.String(), nullable=True),
    sa.Column('meta_valor', sa.String(), nullable=True),
    sa.Column('realizado_tipo', sa.String(), nullable=True),
    sa.Column('realizado_valor', sa.String(), nullable=True),
    sa.Column('descricao_meta', sa.String(), nullable=True),
    sa.Column('descricao_entrega', sa.String(), nullable=True),
    sa.Column('plano_entrega_id', sa.String(), nullable=True),
    sa.Column('unidade_sigla', sa.String(), nullable=True),
    sa.Column('unidade_nome', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.String(), nullable=True),
    sa.Column('grupo_nome', sa.String(), nullable=True),
    sa.Column('grupo_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('di_entregas_id')
    )
    op.create_table('di_planos_entregas',
    sa.Column('di_planos_entregas_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('data_arquivamento', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('di_planos_entregas_id')
    )
    op.create_table('di_planos_trabalho',
    sa.Column('di_planos_trabalho_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('carga_horaria', sa.Float(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('forma_contagem_carga_horaria', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('di_planos_trabalho_id')
    )
    op.create_table('di_tempo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('db_data', sa.Date(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('quinzena', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(), nullable=False),
    sa.Column('mes_nome', sa.String(), nullable=False),
    sa.Column('final_de_semana', sa.Boolean(), nullable=False),
    sa.Column('feriado', sa.Boolean(), nullable=False),
    sa.Column('bimestre', sa.Integer(), nullable=False),
    sa.Column('nome_bimestre', sa.String(), nullable=False),
    sa.Column('trimestre', sa.Integer(), nullable=False),
    sa.Column('nome_trimestre', sa.String(), nullable=False),
    sa.Column('quadrimestre', sa.Integer(), nullable=False),
    sa.Column('nome_quadrimestre', sa.String(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('nome_semestre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('db_data')
    )
    op.create_table('di_trabalhos',
    sa.Column('di_trabalhos_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('atividade_descricao', sa.String(), nullable=True),
    sa.Column('atividade_status', sa.String(), nullable=True),
    sa.Column('tipo_atividade_nome', sa.String(), nullable=True),
    sa.Column('plano_trabalho_consolidacao_status', sa.String(), nullable=True),
    sa.Column('avaliacao_id', sa.String(), nullable=True),
    sa.Column('entrega_id', sa.String(), nullable=True),
    sa.Column('atividade_data_distribuicao', sa.DateTime(), nullable=True),
    sa.Column('atividade_progresso', sa.Float(), nullable=True),
    sa.Column('prazo', sa.Integer(), nullable=True),
    sa.Column('tempo_utilizado', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.String(), nullable=True),
    sa.Column('plano_trabalho_id', sa.String(), nullable=True),
    sa.Column('forca_trabalho', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('di_trabalhos_id')
    )
    op.create_table('di_unidades',
    sa.Column('di_unidades_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('sigla', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('unidade_pai_id', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('data_inativacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('di_unidades_id')
    )
    op.create_table('di_usuarios',
    sa.Column('di_usuarios_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('matricula', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('situacao_funcional', sa.String(), nullable=True),
    sa.Column('data_modificacao', sa.DateTime(), nullable=True),
    sa.Column('modalidade_pgd', sa.String(), nullable=True),
    sa.Column('participa_pgd', sa.String(), nullable=True),
    sa.Column('nome_jornada', sa.String(), nullable=True),
    sa.Column('cod_jornada', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('di_usuarios_id')
    )
    op.create_table('ft_desempenho',
    sa.Column('ft_desempenho_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('di_trabalhos_id', sa.Integer(), nullable=True),
    sa.Column('di_unidades_id', sa.Integer(), nullable=True),
    sa.Column('di_usuarios_id', sa.Integer(), nullable=True),
    sa.Column('di_planos_entregas_id', sa.Integer(), nullable=True),
    sa.Column('di_planos_trabalho_id', sa.Integer(), nullable=True),
    sa.Column('di_avaliacao_id', sa.Integer(), nullable=True),
    sa.Column('di_entregas_id', sa.Integer(), nullable=True),
    sa.Column('di_tempo_dist_id', sa.Integer(), nullable=True),
    sa.Column('prazo', sa.Integer(), nullable=True),
    sa.Column('tempo_utilizado', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ft_desempenho_id')
    )
    op.create_table('ft_entregas',
    sa.Column('ft_entregas_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('di_unidades_id', sa.Integer(), nullable=True),
    sa.Column('di_usuarios_id', sa.Integer(), nullable=True),
    sa.Column('di_planos_entregas_id', sa.Integer(), nullable=True),
    sa.Column('di_planos_trabalho_id', sa.Integer(), nullable=True),
    sa.Column('di_avaliacao_id', sa.Integer(), nullable=True),
    sa.Column('di_trabalhos_id', sa.Integer(), nullable=True),
    sa.Column('di_tempo_ini_id', sa.Integer(), nullable=True),
    sa.Column('di_tempo_fim_id', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('destinatario', sa.String(), nullable=True),
    sa.Column('meta', sa.String(), nullable=True),
    sa.Column('entrega_id', sa.String(), nullable=True),
    sa.Column('unidade_sigla', sa.String(), nullable=True),
    sa.Column('unidade_nome', sa.String(), nullable=True),
    sa.Column('grupo_nome', sa.String(), nullable=True),
    sa.Column('grupo_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ft_entregas_id')
    )
    op.create_table('st_avaliacoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data_avaliacao', sa.DateTime(), nullable=True),
    sa.Column('nota', sa.String(), nullable=True),
    sa.Column('recurso', sa.String(), nullable=True),
    sa.Column('data_recurso', sa.String(), nullable=True),
    sa.Column('avaliador_nome', sa.String(), nullable=True),
    sa.Column('tipo_avaliacao_nome', sa.String(), nullable=True),
    sa.Column('tipo_avaliacao_tipo', sa.String(), nullable=True),
    sa.Column('tipo_avaliacao_nota_descricao', sa.String(), nullable=True),
    sa.Column('plano_entrega_id', sa.String(), nullable=True),
    sa.Column('plano_trabalho_consolidacao_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_entregas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('homologado', sa.Integer(), nullable=True),
    sa.Column('progresso_esperado', sa.Float(), nullable=True),
    sa.Column('progresso_realizado', sa.Float(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('destinatario', sa.String(), nullable=True),
    sa.Column('meta_tipo', sa.String(), nullable=True),
    sa.Column('meta_valor', sa.String(), nullable=True),
    sa.Column('realizado_tipo', sa.String(), nullable=True),
    sa.Column('realizado_valor', sa.String(), nullable=True),
    sa.Column('descricao_meta', sa.String(), nullable=True),
    sa.Column('descricao_entrega', sa.String(), nullable=True),
    sa.Column('plano_entrega_id', sa.String(), nullable=True),
    sa.Column('unidade_sigla', sa.String(), nullable=True),
    sa.Column('unidade_nome', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.String(), nullable=True),
    sa.Column('grupo_nome', sa.String(), nullable=True),
    sa.Column('grupo_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_lotacoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.String(), nullable=True),
    sa.Column('usuario_nome', sa.String(), nullable=True),
    sa.Column('unidade_sigla', sa.String(), nullable=True),
    sa.Column('unidade_nome', sa.String(), nullable=True),
    sa.Column('unidade_uf', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_planos_entregas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('data_arquivamento', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('planejamento_id', sa.String(), nullable=True),
    sa.Column('cadeia_valor_id', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.String(), nullable=True),
    sa.Column('programa_id', sa.String(), nullable=True),
    sa.Column('avaliacao_id', sa.String(), nullable=True),
    sa.Column('okr_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_planos_trabalho',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('carga_horaria', sa.Float(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('forma_contagem_carga_horaria', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('programa_id', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.String(), nullable=True),
    sa.Column('tipo_modalidade_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_planos_trabalhos_entregas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plano_trabalho_id', sa.String(), nullable=True),
    sa.Column('plano_entrega_entrega_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_trabalhos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('atividade_descricao', sa.String(), nullable=True),
    sa.Column('atividade_status', sa.String(), nullable=True),
    sa.Column('tipo_atividade_nome', sa.String(), nullable=True),
    sa.Column('plano_trabalho_consolidacao_status', sa.String(), nullable=True),
    sa.Column('avaliacao_id', sa.String(), nullable=True),
    sa.Column('entrega_id', sa.String(), nullable=True),
    sa.Column('atividade_data_distribuicao', sa.DateTime(), nullable=True),
    sa.Column('atividade_progresso', sa.Float(), nullable=True),
    sa.Column('prazo', sa.Integer(), nullable=True),
    sa.Column('tempo_utilizado', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.String(), nullable=True),
    sa.Column('plano_trabalho_id', sa.String(), nullable=True),
    sa.Column('forca_trabalho', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_unidades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('unidade_pai_id', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('data_inativacao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('matricula', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('situacao_funcional', sa.String(), nullable=True),
    sa.Column('data_modificacao', sa.DateTime(), nullable=True),
    sa.Column('modalidade_pgd', sa.String(), nullable=True),
    sa.Column('participa_pgd', sa.String(), nullable=True),
    sa.Column('nome_jornada', sa.String(), nullable=True),
    sa.Column('cod_jornada', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tr_entregas_grupos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('palavras_chave', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tr_entregas_palavras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palavra', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tr_ft_entregas',
    sa.Column('ft_entregas_id', sa.Integer(), nullable=False),
    sa.Column('di_unidades_id', sa.Integer(), nullable=True),
    sa.Column('di_usuarios_id', sa.Integer(), nullable=True),
    sa.Column('di_planos_entregas_id', sa.Integer(), nullable=True),
    sa.Column('di_planos_trabalho_id', sa.Integer(), nullable=True),
    sa.Column('di_avaliacao_id', sa.Integer(), nullable=True),
    sa.Column('di_trabalhos_id', sa.Integer(), nullable=True),
    sa.Column('di_tempo_ini_id', sa.Integer(), nullable=True),
    sa.Column('di_tempo_fim_id', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('destinatario', sa.String(), nullable=True),
    sa.Column('meta', sa.String(), nullable=True),
    sa.Column('entrega_id', sa.String(), nullable=True),
    sa.Column('unidade_sigla', sa.String(), nullable=True),
    sa.Column('unidade_nome', sa.String(), nullable=True),
    sa.Column('grupo_nome', sa.String(), nullable=True),
    sa.Column('grupo_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ft_entregas_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tr_ft_entregas')
    op.drop_table('tr_entregas_palavras')
    op.drop_table('tr_entregas_grupos')
    op.drop_table('st_usuarios')
    op.drop_table('st_unidades')
    op.drop_table('st_trabalhos')
    op.drop_table('st_planos_trabalhos_entregas')
    op.drop_table('st_planos_trabalho')
    op.drop_table('st_planos_entregas')
    op.drop_table('st_lotacoes')
    op.drop_table('st_entregas')
    op.drop_table('st_avaliacoes')
    op.drop_table('ft_entregas')
    op.drop_table('ft_desempenho')
    op.drop_table('di_usuarios')
    op.drop_table('di_unidades')
    op.drop_table('di_trabalhos')
    op.drop_table('di_tempo')
    op.drop_table('di_planos_trabalho')
    op.drop_table('di_planos_entregas')
    op.drop_table('di_entregas')
    op.drop_table('di_avaliacoes')
    # ### end Alembic commands ###
